lending_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'lending'

urlpatterns = [
    url(r'^$', views.country, name='index'),
    # url(r'^state/(?P<pk>[0-9]+)/$', views.state, name='state'),
    url(r'^state/(?P<state>\D+)/$', views.state, name='state'),
    url(r'^country$', views.country, name='country'),
    url(r'^bank_detail/(?P<bank_id>[0-9]+)/$', views.bank_detail, name='bank_detail'),
    url(r'^location$', views.location, name='location'),
    url(r'^about$', views.about, name='about'),
    url(r'^comparison/(?P<bank1_id>[0-9]+)/(?P<bank2_id>[0-9]+)/$', views.bank_comparison, name='bank_comparison'),
]

lending_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('lending_app.urls'))

]

lending_app/models.py
from django.db import models


class State(models.Model):
    name = models.CharField(max_length=100)
    number_of_banks = models.IntegerField(default=0)
    average_score = models.FloatField()


class Bank(models.Model):
    state = models.ForeignKey(State)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    number_of_employees = models.IntegerField(default=0)
    number_domestic_offices = models.IntegerField(default=0)
    total_assets = models.BigIntegerField(default=0)
    total_liability = models.BigIntegerField(default=0)

    total_deposits = models.BigIntegerField(default=0)
    common_stock = models.BigIntegerField(default=0)
    derivatives = models.BigIntegerField(default=0)
    total_securities = models.BigIntegerField(default=0)
    asset_backed_securities = models.BigIntegerField(default=0)
    mortgage_backed_securities = models.BigIntegerField(default=0)
    family_residential_loans = models.BigIntegerField(default=0)
    home_equity_loans = models.BigIntegerField(default=0)
    adjustable_rate_loans_secured_by_family_residential = models.BigIntegerField(default=0)

    total_num_loans_small = models.BigIntegerField(default=0)
    total_num_loans_micro = models.BigIntegerField(default=0)
    total_num_loans_farm = models.BigIntegerField(default=0)

    total_loans = models.BigIntegerField(default=0)
    total_amount_individual = models.BigIntegerField(default=0)
    total_amount_small = models.BigIntegerField(default=0)
    total_amount_micro = models.BigIntegerField(default=0)
    total_amount_farm = models.BigIntegerField(default=0)

    individual_loan_percentage = models.FloatField()
    small_loan_percentage = models.FloatField()
    micro_loan_percentage = models.FloatField()
    farm_loan_percentage = models.FloatField()

    other_real_estate_owned = models.BigIntegerField(default=0)
    real_estate_acquired = models.BigIntegerField(default=0)
    other_real_estate_owned_family = models.BigIntegerField(default=0)
    other_real_estate_owned_multi_family_residential = models.BigIntegerField(default=0)
    other_real_estate_owned_commercial_real_estate = models.BigIntegerField(default=0)
    other_real_estate_owned_construction_development = models.BigIntegerField(default=0)
    other_real_estate_owned_farmland = models.BigIntegerField(default=0)
    foreclosed_properties_from_GNMA_loans = models.BigIntegerField(default=0)

    net_interest_margin = models.FloatField()
    noninterest_income_to_average_assets = models.FloatField()
    noninterest_expense_to_average_assets = models.FloatField()
    loan_and_lease_loss_provision_to_assets = models.FloatField()
    net_operating_income_to_assets = models.FloatField()

    return_on_assets = models.FloatField()
    return_on_equity = models.FloatField()

    retained_earnings_to_average_equity = models.FloatField()
    net_charge_offs_to_loans = models.FloatField()
    net_loans_and_leases_to_total_assets = models.FloatField()
    net_loans_and_leases_to_deposits = models.FloatField()
    net_loans_and_leases_to_core_deposits = models.FloatField()
    total_domestic_deposits_to_total_assets = models.FloatField()
    average_total_assets = models.FloatField()
    average_earning_assets = models.FloatField()
    average_equity = models.FloatField()
    average_total_loans = models.FloatField()

    total_complaints = models.IntegerField(default=0)
    score = models.FloatField()

    # @property
    # def score1(self):
    #     if self.total_complaints >= 4000:
    #          self.score = (self.score * 190 - (self.total_complaints/4500))
    #     elif self.total_complaints <= 4000 and self.total_complaints >= 100:
    #          self.score = (self.score * 300 - (self.total_complaints/4000))
    #     else:
    #         self.score = (self.score * 225 - (self.total_complaints/4))
    #     return self.score

lending_app/views.py
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Q


from .models import Bank, State


def index(request):

    if request.POST:
        banks = request.POST.getlist('bankArray[]')

        queries = [Q(name__icontains=bank) for bank in banks]
        query = queries.pop()
        for item in queries:
            query |= item

        filtered_banks = Bank.objects.filter(query)
        data = serializers.serialize('json', filtered_banks)
        request.session['bank_list'] = data
        # RETURNS TO AJAX CALL
        return HttpResponseRedirect(reverse('lending:location'))

    states = State.objects.all()
    context = {
        'states': states,
    }
    return render(request, 'index.html', context)


def state(request, state):
    state_name = state
    state = State.objects.get(name=state_name)
    banks = Bank.objects.filter(state=state).order_by('-return_on_equity')
    context = {
        'banks': banks
    }
    return render(request, 'state.html', context)


def location(request):
    serialized_banks = request.session.get('bank_list')
    deserialized_banks = serializers.deserialize("json", serialized_banks)
    bank_list = [bank.object for bank in deserialized_banks]
    context = {
        'bank_list': bank_list
    }
    return render(request, 'location.html', context)


def country(request):

    if request.POST:
        banks = request.POST.getlist('bankArray[]')

        queries = [Q(name__icontains=bank) for bank in banks]
        query = queries.pop()
        for item in queries:
            query |= item

        filtered_banks = Bank.objects.filter(query)
        data = serializers.serialize('json', filtered_banks)
        request.session['bank_list'] = data
        # RETURNS TO AJAX CALL
        return HttpResponseRedirect(reverse('lending:location'))
    state = State.objects.all()
    context = {
        'states': state
    }
    return render(request, 'country.html', context)


def bank_detail(request, bank_id):
    bank_id = int(bank_id)
    bank = Bank.objects.get(id=bank_id)

    if request.POST:
        name = request.POST['bank-name']
        bank_2 = Bank.objects.get(name=name)
        return HttpResponseRedirect(reverse('lending:bank_comparison', kwargs={'bank1_id': bank_id, 'bank2_id': bank_2.id}))

    bank_list = Bank.objects.all()
    context = {
        'bank': bank,
        'bank_list': bank_list
    }
    return render(request, 'bank_detail.html', context)


def about(request):
    context = {}
    return render(request, 'about_us.html', context)


def bank_comparison(request, bank1_id, bank2_id):
    bank_1 = Bank.objects.get(id=bank1_id)
    bank_2 = Bank.objects.get(id=bank2_id)
    context = {
        'bank_1': bank_1,
        'bank_2': bank_2
        }
    return render(request, 'bank_comparison.html', context)

lending_app/templates/about_us.html
{% extends 'base.html' %} {% load static %} {% block body %}

<!-- Carousel -->
<div class="col-xs-8 col-xs-push-2">
<div class="carousel-container">
    <div class="info">
        <h4>
      A website that gives consumers tools to evaluate banks based on a set of criteria.  For example, local commitment, location, size, financial strength, lending data and number of complaints.  The data is presented in an intuitive manner that allows for comparison banks.
        </h4>
    </div>
    <br>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1" class></li>
            <li data-target="#myCarousel" data-slide-to="2" class></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img class="first-slide carousel-image" src="{% static 'img/richard.jpg' %}" alt="First slide">
                <div class="container">
                    <div class="carousel-caption">
                        <h3 class="carousel-text">Richard T. Brown Jr</h3>
                        <!-- <p class="carousel-text">Test text 1</p> -->
                    </div>
                </div>
            </div>
            <div class="item">
                <img class="second-slide carousel-image" src="{% static 'img/jon.jpg' %}" alt="Second slide">
                <div class="container">
                    <div class="carousel-caption">
                        <h3 class="carousel-text">Jon Alligood</h3>
                        <!-- <p class="carousel-text">Test text 2</p> -->
                    </div>
                </div>
            </div>
            <div class="item">
                <img class="third-slide carousel-image" src="{% static 'img/andrew.jpg' %}" alt="Third slide">
                <div class="container">
                    <div class="carousel-caption">
                        <h3 class="carousel-text">Andrew Musicant</h3>
                        <!-- <p class="carousel-text">Test text 3</p> -->
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="headerdata">
        <br>
        <h2>Data Sources
            </h2>
        <div class="info">
            <h4><a href='https://cdr.ffiec.gov/public/'>The FFIEC Central Data Repository's</a> Public Data Distribution web site. Through this we obtained Reports of Condition and Income (Call Reports) and Uniform Bank Performance Reports (UBPRs) for most FDIC-insured institutions. The information available on this site is updated to reflect the most recent data for both prior and current periods.
            </h4>
            <br>
            <h4>The Home Mortgage Disclosure Act (HMDA) requires financial institutions to maintain, report, and publicly disclose information about mortgages. The <a href='http://www.consumerfinance.gov/'>Consumer Financial Protection Bureau</a>(CFPB) mantains a public database for all financial institutions.
            </h4>
        </div>
    </div>
</div>


        <!-- Carousel -->
        {% endblock %}

lending_app/templates/bank_comparison.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery-ui.structure.min.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery-ui.theme.min.css' %}">
<link rel="stylesheet" href="{% static 'css/nv.d3.css' %}">
<link rel="stylesheet" href="{% static 'css/bank_comparison.css' %}">
{% endblock %}

{% block body %}
<div class="col-md-6 middle-line-right">
  <style type="text/css">
      .dollars:before { content:'$'; }
  </style>
  <div class="bank-detail">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="bank-large">
            <h1>{{ bank_1.name }}: &nbsp{% widthratio bank_1.score|floatformat:2 1 100 %}%</h1>
            <hr id="title-rule">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="bank-info">
          <div class="col-md-12">
            <div class="bank-info-row vcenter">
              <h3>Total Assets: <span class="dollars">{{ bank_1.total_assets|intcomma }}</span></h3>
            </div>
            <div class="bank-info-row vcenter">
              <h3>Number of Branches: {{ bank_1.number_domestic_offices|intcomma }}</h3>
            </div>
            <div class="bank-info-row vcenter">
              <h3>Number of Employees: {{ bank_1.number_of_employees|intcomma }}</h3>
            </div>
            <div class="bank-info-row vcenter">
              <h3>Number of Complaints: {{ bank_1.total_complaints }}</h3>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="pie-chart">
            <h3>Percentage of Loans for Bank</h3>
            <div id="pieChart1"></div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="bar-chart">
            <h3>Total Number of Loans</h3>
            <div id="chart1">
              <svg></svg>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="bank-data">
          <div class="col-md-12">
            <div class="bank-info-col">
              <h5>Total Liability</h5>
              <hr>
              <p><span class="dollars">{{ bank_1.total_liability|intcomma }}</span></p>
              <h5>Return on Equity</h5>
              <hr>
              <p>{{ bank_1.return_on_equity|floatformat:2 }}</p>
              <h5>Total Deposits</h5>
              <hr>
              <p><span class="dollars">{{ bank_1.total_deposits|intcomma }}</span></p>
              <h5>Common Stock</h5>
              <hr>
              <p>{{ bank_1.common_stock|intcomma }}</p>
              <h5>Return on Assets</h5>
              <hr>
              <p>{{ bank_1.return_on_assets|floatformat:2 }}</p>
              <h5>Retained Earnings to Average Equity</h5>
              <hr>
              <p>{{ bank_1.retained_earnings_to_average_equity|floatformat:2 }}</p>
            </div>
          </div>
          <div class="col-md-12">
            <div class="bank-info-col">
              <h5>Number of Residental Real Estate Loans</h5>
              <hr>
              <p>{{ bank_1.family_residential_loans|intcomma }}</p>

              <h5>Home Equity Loans</h5>
              <hr>
              <p>{{ bank_1.home_equity_loans|intcomma }}</p>

              <h5>Adjustable Rate Residental Loans</h5>
              <hr>
              <p>{{ bank_1.adjustable_rate_loans_secured_by_family_residential|intcomma }}</p>
              <h5>Foreclosed Residental Loans</h5>
              <hr>
              <p>{{ bank_1.other_real_estate_owned_family|intcomma }}</p>
              <h5>Foreclosed Commerical Loans</h5>
              <hr>
              <p>{{ bank_1.other_real_estate_owned_commercial_real_estate|intcomma }}</p>
              <h5>Foreclosed Farm Loans</h5>
              <hr>
              <p>{{ bank_1.other_real_estate_owned_farmland|intcomma }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-md-6">
  <style type="text/css">
      .dollars:before { content:'$'; }
  </style>
  <div class="bank-detail">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="bank-large">
            <h1>{{ bank_2.name }}: &nbsp{% widthratio bank_2.score|floatformat:2 1 100 %}%</h1>
            <hr id="title-rule">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="bank-info">
          <div class="col-md-12">
            <div class="bank-info-row vcenter">
              <h3>Total Assets: <span class="dollars">{{ bank_2.total_assets|intcomma }}</span></h3>
            </div>
            <div class="bank-info-row vcenter">
              <h3>Number of Branches: {{ bank_2.number_domestic_offices|intcomma }}</h3>
            </div>
            <div class="bank-info-row vcenter">
              <h3>Number of Employees: {{ bank_2.number_of_employees|intcomma }}</h3>
            </div>
            <div class="bank-info-row vcenter">
              <h3>Number of Complaints: {{ bank_2.total_complaints }}</h3>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="pie-chart">
            <h3>Percentage of Loans for Bank</h3>
            <div id="pieChart2"></div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="bar-chart">
            <h3>Total Number of Loans</h3>
            <div id="chart2">
              <svg></svg>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="bank-data">
          <div class="col-md-12">
            <div class="bank-info-col">
              <h5>Total Liability</h5>
              <hr>
              <p><span class="dollars">{{ bank_2.total_liability|intcomma }}</span></p>
              <h5>Return on Equity</h5>
              <hr>
              <p>{{ bank_2.return_on_equity|floatformat:2 }}</p>
              <h5>Total Deposits</h5>
              <hr>
              <p><span class="dollars">{{ bank_2.total_deposits|intcomma }}</span></p>
              <h5>Common Stock</h5>
              <hr>
              <p>{{ bank_2.common_stock|intcomma }}</p>
              <h5>Return on Assets</h5>
              <hr>
              <p>{{ bank_2.return_on_assets|floatformat:2 }}</p>
              <h5>Retained Earnings to Average Equity</h5>
              <hr>
              <p>{{ bank_2.retained_earnings_to_average_equity|floatformat:2 }}</p>
            </div>
          </div>
          <div class="col-md-12">
            <div class="bank-info-col">
              <h5>Number of Residental Real Estate Loans</h5>
              <hr>
              <p>{{ bank_2.family_residential_loans|intcomma }}</p>

              <h5>Home Equity Loans</h5>
              <hr>
              <p>{{ bank_2.home_equity_loans|intcomma }}</p>

              <h5>Adjustable Rate Residental Loans</h5>
              <hr>
              <p>{{ bank_2.adjustable_rate_loans_secured_by_family_residential|intcomma }}</p>
              <h5>Foreclosed Residental Loans</h5>
              <hr>
              <p>{{ bank_2.other_real_estate_owned_family|intcomma }}</p>
              <h5>Foreclosed Commerical Loans</h5>
              <hr>
              <p>{{ bank_2.other_real_estate_owned_commercial_real_estate|intcomma }}</p>
              <h5>Foreclosed Farm Loans</h5>
              <hr>
              <p>{{ bank_2.other_real_estate_owned_farmland|intcomma }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.4.4/d3.min.js"></script>
<script src="{% static 'js/d3pie.min.js' %}"></script>
<script src="{% static 'js/nv.d3.js' %}"></script>

<script>
var pieData1 = {
  micro: {{bank_1.micro_loan_percentage}},
  small: {{bank_1.small_loan_percentage}},
  farm: {{bank_1.farm_loan_percentage}},
  individual: {{bank_1.individual_loan_percentage}}
}
var pieData2 = {
  micro: {{bank_2.micro_loan_percentage}},
  small: {{bank_2.small_loan_percentage}},
  farm: {{bank_2.farm_loan_percentage}},
  individual: {{bank_2.individual_loan_percentage}}
}
</script>
<script src="{% static 'js/drawPieChart.js' %}"></script>

<script>
  var bankData1 = {
    micro: {{bank_1.total_num_loans_micro}},
    small: {{bank_1.total_num_loans_small}},
    farm: {{bank_1.total_num_loans_farm}}
  }
  var bankData2 = {
    micro: {{bank_2.total_num_loans_micro}},
    small: {{bank_2.total_num_loans_small}},
    farm: {{bank_2.total_num_loans_farm}}
  }
</script>
<script src="{% static 'js/drawBarChart.js' %}"></script>

{% endblock %}

lending_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Invest Local</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Open+Sans" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <nav class="navbar navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'lending:index' %}"><img border="0" alt="Invest Local" src="{% static 'img/lblogo.gif' %}" width="114" height="40"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li class="active"><a href="{% url 'lending:index' %}" class="button1">Invest Local<span class="sr-only">(current)</span></a></li>
          <li class="active"><a href="{% url 'lending:about' %}" class="button3">About<span class="sr-only">(current)</span></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <form class="navbar-form navbar-right" role="search">
      <div class="input-group">
        {% csrf_token %}
        <input id="address" class="form-control" type="search" value="" placeholder="Address or Zip Code">
        <span class="input-group-btn">
        <input type="button" class="btn btn-default" value="Search" onclick="codeAddress()">
        </span>
      </div>
    </form>
  </div><!-- /.container-fluid -->
</nav>
      {% block body %}
      {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlot5QAMpAAvlhAsr2blWKx5vOOfUVYrg&libraries=places"></script>
    <script src="{% static 'js/csrfcookie.js' %}"></script>
    <script src="{% static 'js/googlemaps.js' %}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

lending_app/templates/country.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
  <div class="title-text">
    <h1>Invest Local</h1>
    <h2>Find banks that help your community</h2>
  </div>
<div id="tooltip"></div><!-- div to hold tooltip. -->
<div><svg width="960" height="600" id="statesvg" class="usa-map"></svg></div>
<div class="right-key">
  <svg id="key"></svg>
  <h5 class="legend">Bank Density</h5>
</div>


{% endblock %}
{% block scripts %}
<script>
var numOfBanks = {};
var avgOfBanks = {};
{% for state in states %}
  numOfBanks['{{ state.name }}']={{ state.number_of_banks }}
  avgOfBanks['{{ state.name }}']={% widthratio state.average_score|floatformat:2 1 100 %}
{% endfor %}
</script>
<script src="../static/js/uStates.js"></script> <!-- creates uStates. -->
<script src="https://d3js.org/d3.v3.min.js"></script>
<script src="../static/js/country.js"></script>
<script src="../static/js/testjs.js"></script>
{% endblock %}

lending_app/templates/location.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
{% endblock %}

{% block body %}
<div class="datatable">
  <table id="myTable" class="display" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Total Assets</th>
        <th>Bank Score Ranking</th>
      </tr>
    </thead>
    <tbody>
      {% for bank in bank_list %}
        <tr>
          <td><a href="{% url 'lending:bank_detail' bank.id %}">{{ bank.name }}</a></td>
          <td>{{ bank.total_assets|intcomma }}</td>
          <td>{% widthratio bank.score|floatformat:2 1 100 %}%</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/dataTablesBase.js' %}"></script>
<script src="{% static 'js/datatable.js' %}"></script>
{% endblock %}

lending_app/templates/state.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
{% endblock %}

{% block body %}
<div class="datatable">
  <table id="myTable" class="display" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Total Assets</th>
        <th>Bank Score Ranking</th>
      </tr>
    </thead>
    <tbody>
      {% for bank in banks %}
        <tr>
          <td><a href="{% url 'lending:bank_detail' bank.id %}">{{ bank.name }}</a></td>
          <td>{{ bank.total_assets|intcomma }}</td>
          <td>{% widthratio bank.score|floatformat:2 1 100 %}%</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/dataTablesBase.js' %}"></script>
<script src="{% static 'js/datatable.js' %}"></script>
{% endblock %}

lending_app/templates/testhtml.html
<!DOCTYPE html>
<meta charset="utf-8">


<html>
  <head>
    <link href="testcss.css" rel="stylesheet"/>
  </head>

  <body>
      <svg id="key">
      </svg>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <script src="testjs.js"></script>
  </body>
</html>